import { describe, expect, it } from 'vitest';
import { normalizeSnapshot, serializeSubmission } from '../../server/community-server.mjs';

describe('community server snapshot contract', () => {
  it('accepts the current v2 community snapshot shape', () => {
    expect(normalizeSnapshot({
      presetId: 'oak',
      params: {
        randomSeed: 58,
        colorRandomness: 0.2,
        height: 18,
        crownWidth: 17,
        crownDepth: 0.62,
        trunkBaseRadius: 2,
        trunkTaper: 0.46,
        trunkLean: 0,
        trunkLeanDirection: 0,
        clearTrunkHeight: 0.26,
        trunkCurvature: 0.11,
        trunkNoise: 0.22,
        primaryBranchCount: 5,
        branchAngle: 52,
        branchAngleVariance: 12,
        branchLengthRatio: 0.82,
        branchOrderDepth: 3,
        branchDensity: 0.56,
        branchDroop: 0.1,
        apicalDominance: 0.18,
        crownShape: 'ovoid',
        crownFullness: 0.82,
        leafClusterRadius: 2.6,
        leafDensity: 0.84,
        interiorLeafPruning: 0.3,
        minBranchThickness: 1,
        leafCleanup: 0.58,
        symmetryAssist: 0.14,
        buildabilityBias: 0.58,
      },
      blockColors: {
        log: '#70492f',
        branch: '#7f5d37',
        leaf: '#5e8744',
        fence: '#7f5d37',
      },
      minecraftPalette: {
        log: 'oak_log',
        branch: 'stripped_oak_log',
        fence: 'oak_fence',
        leaf: 'oak_leaves',
      },
    })).toEqual({
      presetId: 'oak',
      params: {
        randomSeed: 58,
        colorRandomness: 0.2,
        height: 18,
        crownWidth: 17,
        crownDepth: 0.62,
        trunkBaseRadius: 2,
        trunkTaper: 0.46,
        trunkLean: 0,
        trunkLeanDirection: 0,
        clearTrunkHeight: 0.26,
        trunkCurvature: 0.11,
        trunkNoise: 0.22,
        primaryBranchCount: 5,
        branchAngle: 52,
        branchAngleVariance: 12,
        branchLengthRatio: 0.82,
        branchOrderDepth: 3,
        branchDensity: 0.56,
        branchDroop: 0.1,
        apicalDominance: 0.18,
        crownShape: 'ovoid',
        crownFullness: 0.82,
        leafClusterRadius: 2.6,
        leafDensity: 0.84,
        interiorLeafPruning: 0.3,
        minBranchThickness: 1,
        leafCleanup: 0.58,
        symmetryAssist: 0.14,
        buildabilityBias: 0.58,
      },
      blockColors: {
        log: '#70492f',
        branch: '#7f5d37',
        leaf: '#5e8744',
        fence: '#7f5d37',
      },
      minecraftPalette: {
        log: 'oak_log',
        branch: 'stripped_oak_log',
        fence: 'oak_fence',
        leaf: 'oak_leaves',
      },
    });
  });

  it('serializes submissions with the full snapshot payload', () => {
    const submission = serializeSubmission({
      id: 'submission-1',
      creationName: 'Canopy Oak',
      authorName: 'Ari',
      status: 'approved',
      createdAt: '2026-03-30T00:00:00.000Z',
      reviewedAt: '2026-03-30T01:00:00.000Z',
      snapshot: {
        presetId: 'spruce',
        params: {
          randomSeed: 131,
          colorRandomness: 0.15,
          height: 22,
          crownWidth: 8,
          crownDepth: 0.82,
          trunkBaseRadius: 1.25,
          trunkTaper: 0.9,
          trunkLean: 0,
          trunkLeanDirection: 0,
          clearTrunkHeight: 0.1,
          trunkCurvature: 0.02,
          trunkNoise: 0.05,
          primaryBranchCount: 11,
          branchAngle: 64,
          branchAngleVariance: 4,
          branchLengthRatio: 0.56,
          branchOrderDepth: 2,
          branchDensity: 0.9,
          branchDroop: 0.16,
          apicalDominance: 0.98,
          crownShape: 'conical',
          crownFullness: 0.9,
          leafClusterRadius: 1.7,
          leafDensity: 0.92,
          interiorLeafPruning: 0.2,
          minBranchThickness: 1,
          leafCleanup: 0.62,
          symmetryAssist: 0.34,
          buildabilityBias: 0.76,
        },
        blockColors: {
          log: '#5a3925',
          branch: '#66462f',
          leaf: '#2f5632',
          fence: '#66462f',
        },
        minecraftPalette: {
          log: 'spruce_log',
          branch: 'stripped_spruce_log',
          fence: 'spruce_fence',
          leaf: 'spruce_leaves',
        },
      },
    });

    expect(submission.snapshot.blockColors.fence).toBe('#66462f');
    expect(submission.snapshot.minecraftPalette.fence).toBe('spruce_fence');
  });
});
