import type { Axis, BlockType, MinecraftPalette, TreeParams, VoxelStore } from './types';
import { unpack } from './pack';

type ExportBlock = { x: number; y: number; z: number; type: string };

type ExportJSON = {
  blocks: ExportBlock[];
  meta: {
    totalBlocks: number;
    height: number;
    width: number;
    depth: number;
    layerCount: number;
  };
};

type NbtTag =
  | { type: 'byte'; value: number }
  | { type: 'int'; value: number }
  | { type: 'long'; value: bigint }
  | { type: 'string'; value: string }
  | { type: 'list'; childType: NbtTagType; value: NbtTag[] }
  | { type: 'compound'; value: Array<[string, NbtTag]> }
  | { type: 'longArray'; value: bigint[] };

type NbtTagType = NbtTag['type'];

const NBT_TAG_IDS: Record<NbtTagType, number> = {
  byte: 1,
  int: 3,
  long: 4,
  string: 8,
  list: 9,
  compound: 10,
  longArray: 12,
};

/**
 * Export voxel data as a JSON string with block coordinates and metadata.
 */
export function exportJSON(store: VoxelStore, _params: TreeParams): string {
  void _params;
  const blocks: ExportBlock[] = [];

  const sortedYs = Array.from(store.layers.keys()).sort((a, b) => a - b);
  for (const y of sortedYs) {
    const layer = store.layers.get(y)!;
    for (const [key, type] of layer) {
      const [x, z] = unpack(key);
      blocks.push({ x, y, z, type });
    }
  }

  const data: ExportJSON = {
    blocks,
    meta: {
      totalBlocks: store.count,
      height: store.bounds.maxY - store.bounds.minY + 1,
      width: store.bounds.maxX - store.bounds.minX + 1,
      depth: store.bounds.maxZ - store.bounds.minZ + 1,
      layerCount: store.layers.size,
    },
  };

  return JSON.stringify(data, null, 2);
}

/**
 * Export a human-readable per-layer build guide.
 */
export function exportTextGuide(store: VoxelStore): string {
  const lines: string[] = [];
  lines.push('=== TreeVoxel Build Guide ===');
  lines.push(`Total blocks: ${store.count}`);
  lines.push(`Layers: ${store.layers.size}`);
  lines.push('');

  const sortedYs = Array.from(store.layers.keys()).sort((a, b) => a - b);
  for (const y of sortedYs) {
    const layer = store.layers.get(y)!;
    lines.push(`--- Layer Y=${y} (${layer.size} blocks) ---`);

    const byType: Record<string, string[]> = {};
    for (const [key, type] of layer) {
      const [x, z] = unpack(key);
      if (!byType[type]) byType[type] = [];
      byType[type].push(`(${x}, ${z})`);
    }

    for (const [type, coords] of Object.entries(byType)) {
      lines.push(`  ${type}: ${coords.join(' ')}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

export function exportLitematic(store: VoxelStore, palette: MinecraftPalette): Uint8Array<ArrayBuffer> {
  const sizeX = store.bounds.maxX - store.bounds.minX + 1;
  const sizeY = store.bounds.maxY - store.bounds.minY + 1;
  const sizeZ = store.bounds.maxZ - store.bounds.minZ + 1;
  const volume = sizeX * sizeY * sizeZ;

  const stateToIndex = new Map<string, number>();
  const paletteStates: string[] = ['minecraft:air'];
  stateToIndex.set('minecraft:air', 0);

  const sortedYs = Array.from(store.layers.keys()).sort((a, b) => a - b);
  for (const y of sortedYs) {
    const layer = store.layers.get(y)!;
    const axisLayer = store.axis.get(y);
    const connectivityLayer = store.fenceConnectivity.get(y);
    for (const [key, type] of layer) {
      const state = buildBlockState(type, palette, axisLayer?.get(key), connectivityLayer?.get(key));
      if (!stateToIndex.has(state)) {
        stateToIndex.set(state, paletteStates.length);
        paletteStates.push(state);
      }
    }
  }

  const bitsPerBlock = Math.max(2, Math.ceil(Math.log2(Math.max(1, paletteStates.length))));
  const totalBits = volume * bitsPerBlock;
  const blockStates = Array.from({ length: Math.ceil(totalBits / 64) }, () => 0n);

  for (const y of sortedYs) {
    const layer = store.layers.get(y)!;
    const axisLayer = store.axis.get(y);
    const connectivityLayer = store.fenceConnectivity.get(y);
    for (const [key, type] of layer) {
      const [x, z] = unpack(key);
      const localX = x - store.bounds.minX;
      const localY = y - store.bounds.minY;
      const localZ = z - store.bounds.minZ;
      const blockIndex = localY * sizeX * sizeZ + localZ * sizeX + localX;
      const paletteIndex = stateToIndex.get(
        buildBlockState(type, palette, axisLayer?.get(key), connectivityLayer?.get(key)),
      )!;
      writePackedValue(blockStates, blockIndex, bitsPerBlock, paletteIndex);
    }
  }

  const blockStatePalette = paletteStates.map(parseBlockState);
  const timestamp = BigInt(store.count * 1000 + volume);

  const root = compound([
    ['Version', intTag(6)],
    ['SubVersion', intTag(1)],
    ['MinecraftDataVersion', intTag(3955)],
    ['Metadata', compound([
      ['Name', stringTag('TreeVoxel Export')],
      ['Author', stringTag('TreeVoxel')],
      ['Description', stringTag('Generated by TreeVoxel')],
      ['EnclosingSize', compound([
        ['x', intTag(sizeX)],
        ['y', intTag(sizeY)],
        ['z', intTag(sizeZ)],
      ])],
      ['TotalBlocks', intTag(store.count)],
      ['TotalVolume', intTag(volume)],
      ['RegionCount', intTag(1)],
      ['TimeCreated', longTag(timestamp)],
      ['TimeModified', longTag(timestamp)],
    ])],
    ['Regions', compound([
      ['tree', compound([
        ['Position', compound([
          ['x', intTag(0)],
          ['y', intTag(0)],
          ['z', intTag(0)],
        ])],
        ['Size', compound([
          ['x', intTag(sizeX)],
          ['y', intTag(sizeY)],
          ['z', intTag(sizeZ)],
        ])],
        ['BlockStatePalette', listTag('compound', blockStatePalette)],
        ['BlockStates', longArrayTag(blockStates)],
        ['Entities', listTag('compound', [])],
        ['TileEntities', listTag('compound', [])],
        ['PendingBlockTicks', listTag('compound', [])],
        ['PendingFluidTicks', listTag('compound', [])],
      ])],
    ])],
  ]);

  return encodeNbtRoot('Litematic', root);
}

function buildBlockState(
  blockType: BlockType,
  palette: MinecraftPalette,
  voxelAxis?: Axis,
  connectivity?: number,
): string {
  if (blockType === 'log' || blockType === 'branch') {
    const blockId = blockType === 'log' ? palette.log : palette.branch;
    return `minecraft:${blockId}[axis=${voxelAxis ?? 'y'}]`;
  }

  if (blockType === 'fence') {
    const mask = connectivity ?? 0;
    const north = (mask & 0b0001) !== 0;
    const south = (mask & 0b0010) !== 0;
    const east = (mask & 0b0100) !== 0;
    const west = (mask & 0b1000) !== 0;
    return `minecraft:${palette.fence}[north=${north},south=${south},east=${east},west=${west}]`;
  }

  return `minecraft:${palette.leaf}[persistent=true,distance=1]`;
}

function parseBlockState(state: string): NbtTag {
  const propertiesStart = state.indexOf('[');
  if (propertiesStart === -1) {
    return compound([['Name', stringTag(state)]]);
  }

  const name = state.slice(0, propertiesStart);
  const propertyEntries = state
    .slice(propertiesStart + 1, -1)
    .split(',')
    .map((entry) => entry.split('=') as [string, string])
    .sort(([a], [b]) => a.localeCompare(b));

  return compound([
    ['Name', stringTag(name)],
    ['Properties', compound(propertyEntries.map(([key, value]) => [key, stringTag(value)]))],
  ]);
}

function writePackedValue(target: bigint[], index: number, bitsPerBlock: number, value: number): void {
  const bitIndex = index * bitsPerBlock;
  const longIndex = Math.floor(bitIndex / 64);
  const bitOffset = bitIndex % 64;
  const mask = (1n << BigInt(bitsPerBlock)) - 1n;
  const encoded = BigInt(value) & mask;

  target[longIndex] |= encoded << BigInt(bitOffset);

  const spillBits = bitOffset + bitsPerBlock - 64;
  if (spillBits > 0) {
    target[longIndex + 1] |= encoded >> BigInt(bitsPerBlock - spillBits);
  }
}

function encodeNbtRoot(name: string, tag: NbtTag): Uint8Array<ArrayBuffer> {
  if (tag.type !== 'compound') {
    throw new Error('NBT root must be a compound tag.');
  }

  const bytes: number[] = [NBT_TAG_IDS.compound];
  pushString(bytes, name);
  encodeTagPayload(bytes, tag);
  return new Uint8Array(bytes) as Uint8Array<ArrayBuffer>;
}

function encodeTagPayload(bytes: number[], tag: NbtTag): void {
  switch (tag.type) {
    case 'byte':
      pushInt8(bytes, tag.value);
      return;
    case 'int':
      pushInt32(bytes, tag.value);
      return;
    case 'long':
      pushInt64(bytes, tag.value);
      return;
    case 'string':
      pushString(bytes, tag.value);
      return;
    case 'longArray':
      pushInt32(bytes, tag.value.length);
      for (const value of tag.value) {
        pushInt64(bytes, value);
      }
      return;
    case 'list':
      bytes.push(NBT_TAG_IDS[tag.childType] ?? 0);
      pushInt32(bytes, tag.value.length);
      for (const entry of tag.value) {
        encodeTagPayload(bytes, entry);
      }
      return;
    case 'compound':
      for (const [name, value] of tag.value) {
        bytes.push(NBT_TAG_IDS[value.type]);
        pushString(bytes, name);
        encodeTagPayload(bytes, value);
      }
      bytes.push(0);
      return;
    default:
      return;
  }
}

function pushString(bytes: number[], value: string): void {
  const encoded = new TextEncoder().encode(value);
  bytes.push((encoded.length >> 8) & 0xff, encoded.length & 0xff);
  bytes.push(...encoded);
}

function pushInt8(bytes: number[], value: number): void {
  bytes.push(value & 0xff);
}

function pushInt32(bytes: number[], value: number): void {
  const normalized = value | 0;
  bytes.push(
    (normalized >>> 24) & 0xff,
    (normalized >>> 16) & 0xff,
    (normalized >>> 8) & 0xff,
    normalized & 0xff,
  );
}

function pushInt64(bytes: number[], value: bigint): void {
  const normalized = BigInt.asIntN(64, value);
  for (let shift = 56n; shift >= 0n; shift -= 8n) {
    bytes.push(Number((normalized >> shift) & 0xffn));
  }
}

function intTag(value: number): NbtTag {
  return { type: 'int', value };
}

function longTag(value: bigint): NbtTag {
  return { type: 'long', value };
}

function stringTag(value: string): NbtTag {
  return { type: 'string', value };
}

function listTag(childType: NbtTagType, value: NbtTag[]): NbtTag {
  return { type: 'list', childType, value };
}

function compound(value: Array<[string, NbtTag]>): NbtTag {
  return { type: 'compound', value };
}

function longArrayTag(value: bigint[]): NbtTag {
  return { type: 'longArray', value };
}
