import type { BlockColors, MinecraftPalette, Preset, TreeParams } from './types';

const DEFAULT_PRESET_COLORS: BlockColors = {
  log: '#6b4226',
  branch: '#8b6914',
  leaf: '#4d9a45',
  fence: '#8b6914',
};

export const DEFAULT_MINECRAFT_PALETTE: MinecraftPalette = {
  log: 'oak_log',
  branch: 'stripped_oak_log',
  fence: 'oak_fence',
  leaf: 'oak_leaves',
};

export const PRESETS: Preset[] = [
  {
    id: 'oak',
    name: 'Oak',
    description: 'Classic rounded oak with a stout trunk, broad scaffolds, and a compact canopy that still reads cleanly at hand-built scale.',
    growthForm: 'rounded decurrent broadleaf',
    blockColors: {
      log: '#70492f',
      branch: '#7f5d37',
      leaf: '#5e8744',
      fence: '#7f5d37',
    },
    minecraftPalette: {
      log: 'oak_log',
      branch: 'stripped_oak_log',
      fence: 'oak_fence',
      leaf: 'oak_leaves',
    },
    params: {
      randomSeed: 58,
      colorRandomness: 0.18,
      height: 16, crownWidth: 16, crownDepth: 0.62, trunkBaseRadius: 2,
      trunkTaper: 0.44, trunkLean: 0, trunkLeanDirection: 0, clearTrunkHeight: 0.24, trunkCurvature: 0.08, trunkNoise: 0.18,
      primaryBranchCount: 8, branchAngle: 50, branchAngleVariance: 10,
      branchLengthRatio: 0.8, branchOrderDepth: 3, branchDensity: 0.7,
      branchDroop: 0.08, apicalDominance: 0.18,
      crownShape: 'ovoid', crownFullness: 0.85, leafClusterRadius: 2.4,
      leafDensity: 0.82, interiorLeafPruning: 0.3,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.55, buildabilityBias: 0.72,
    },
  },
  {
    id: 'dark_oak',
    name: 'Dark Oak',
    description: 'Dense dark oak with a thick trunk, strong lateral limbs, and a low irregular canopy that feels like a compact roof of leaves.',
    growthForm: 'heavy decurrent broadleaf',
    blockColors: {
      log: '#3e2912',
      branch: '#5a4428',
      leaf: '#456b32',
      fence: '#5a4428',
    },
    minecraftPalette: {
      log: 'dark_oak_log',
      branch: 'stripped_dark_oak_log',
      fence: 'dark_oak_fence',
      leaf: 'dark_oak_leaves',
    },
    params: {
      randomSeed: 184,
      colorRandomness: 0.16,
      height: 17, crownWidth: 20, crownDepth: 0.64, trunkBaseRadius: 2.5,
      trunkTaper: 0.4, trunkLean: 0, trunkLeanDirection: 0, clearTrunkHeight: 0.22, trunkCurvature: 0.1, trunkNoise: 0.2,
      primaryBranchCount: 10, branchAngle: 48, branchAngleVariance: 14,
      branchLengthRatio: 0.92, branchOrderDepth: 3, branchDensity: 0.8,
      branchDroop: 0.14, apicalDominance: 0.12,
      crownShape: 'irregular', crownFullness: 0.92, leafClusterRadius: 2.7,
      leafDensity: 0.9, interiorLeafPruning: 0.22,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.45, buildabilityBias: 0.76,
    },
  },
  {
    id: 'spruce',
    name: 'Spruce',
    description: 'Tall narrow spruce with a strict leader, short upper tiers, and a clean conical silhouette tuned away from overbusy twig noise.',
    growthForm: 'excurrent conifer',
    blockColors: {
      log: '#5a3925',
      branch: '#66462f',
      leaf: '#2f5632',
      fence: '#66462f',
    },
    minecraftPalette: {
      log: 'spruce_log',
      branch: 'stripped_spruce_log',
      fence: 'spruce_fence',
      leaf: 'spruce_leaves',
    },
    params: {
      randomSeed: 131,
      colorRandomness: 0.12,
      height: 19, crownWidth: 10, crownDepth: 0.84, trunkBaseRadius: 1.25,
      trunkTaper: 0.9, trunkLean: 0, trunkLeanDirection: 0, clearTrunkHeight: 0.08, trunkCurvature: 0.02, trunkNoise: 0.04,
      primaryBranchCount: 20, branchAngle: 62, branchAngleVariance: 4,
      branchLengthRatio: 0.54, branchOrderDepth: 3, branchDensity: 0.85,
      branchDroop: 0.16, apicalDominance: 0.98,
      crownShape: 'conical', crownFullness: 0.95, leafClusterRadius: 1.6,
      leafDensity: 0.94, interiorLeafPruning: 0.24,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.7, buildabilityBias: 0.82,
    },
  },
  {
    id: 'birch',
    name: 'Birch',
    description: 'Slender birch with a straight pale trunk, light upward branching, and a compact airy canopy rather than a bulky leaf ball.',
    growthForm: 'slender broadleaf',
    blockColors: {
      log: '#d5cdb4',
      branch: '#c8b77d',
      leaf: '#6d9e47',
      fence: '#c8b77d',
    },
    minecraftPalette: {
      log: 'birch_log',
      branch: 'stripped_birch_log',
      fence: 'birch_fence',
      leaf: 'birch_leaves',
    },
    params: {
      randomSeed: 71,
      colorRandomness: 0.14,
      height: 17, crownWidth: 9, crownDepth: 0.45, trunkBaseRadius: 1.25,
      trunkTaper: 0.72, trunkLean: 0, trunkLeanDirection: 0, clearTrunkHeight: 0.42, trunkCurvature: 0.03, trunkNoise: 0.06,
      primaryBranchCount: 8, branchAngle: 34, branchAngleVariance: 7,
      branchLengthRatio: 0.55, branchOrderDepth: 2, branchDensity: 0.65,
      branchDroop: 0.04, apicalDominance: 0.68,
      crownShape: 'ovoid', crownFullness: 0.76, leafClusterRadius: 1.8,
      leafDensity: 0.74, interiorLeafPruning: 0.42,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.6, buildabilityBias: 0.84,
    },
  },
  {
    id: 'acacia',
    name: 'Acacia',
    description: 'Savanna acacia with a split trunk line, upward-reaching limbs, and a broad flat crown that reads as layered pads instead of a sphere.',
    growthForm: 'vase broadleaf',
    blockColors: {
      log: '#676157',
      branch: '#b05d3b',
      leaf: '#5c7f37',
      fence: '#b05d3b',
    },
    minecraftPalette: {
      log: 'acacia_log',
      branch: 'stripped_acacia_log',
      fence: 'acacia_fence',
      leaf: 'acacia_leaves',
    },
    params: {
      randomSeed: 219,
      colorRandomness: 0.16,
      height: 14, crownWidth: 18, crownDepth: 0.42, trunkBaseRadius: 1.6,
      trunkTaper: 0.5, trunkLean: 7, trunkLeanDirection: 35, clearTrunkHeight: 0.34, trunkCurvature: 0.2, trunkNoise: 0.18,
      primaryBranchCount: 6, branchAngle: 72, branchAngleVariance: 12,
      branchLengthRatio: 1.1, branchOrderDepth: 2, branchDensity: 0.7,
      branchDroop: 0.04, apicalDominance: 0.12,
      crownShape: 'vase', crownFullness: 0.78, leafClusterRadius: 2.4,
      leafDensity: 0.75, interiorLeafPruning: 0.36,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.4, buildabilityBias: 0.8,
    },
  },
  {
    id: 'jungle',
    name: 'Jungle',
    description: 'Tall small-form jungle tree with a long clean trunk, higher canopy start, and stronger branching than birch or spruce without drifting into mega-jungle scale.',
    growthForm: 'tall tropical broadleaf',
    blockColors: {
      log: '#564419',
      branch: '#ac8850',
      leaf: '#30801a',
      fence: '#ac8850',
    },
    minecraftPalette: {
      log: 'jungle_log',
      branch: 'stripped_jungle_log',
      fence: 'jungle_fence',
      leaf: 'jungle_leaves',
    },
    params: {
      randomSeed: 304,
      colorRandomness: 0.18,
      height: 20, crownWidth: 14, crownDepth: 0.5, trunkBaseRadius: 1.75,
      trunkTaper: 0.56, trunkLean: 2, trunkLeanDirection: 95, clearTrunkHeight: 0.42, trunkCurvature: 0.09, trunkNoise: 0.12,
      primaryBranchCount: 7, branchAngle: 42, branchAngleVariance: 10,
      branchLengthRatio: 0.86, branchOrderDepth: 3, branchDensity: 0.7,
      branchDroop: 0.12, apicalDominance: 0.46,
      crownShape: 'ovoid', crownFullness: 0.85, leafClusterRadius: 2.3,
      leafDensity: 0.84, interiorLeafPruning: 0.26,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.4, buildabilityBias: 0.7,
    },
  },
  {
    id: 'cherry_blossom',
    name: 'Cherry Blossom',
    description: 'Wide ornamental cherry with a gently vaulted crown, pink foliage masses, and enough trunk visibility to stay buildable instead of becoming a solid pastel blob.',
    growthForm: 'ornamental broadleaf',
    blockColors: {
      log: '#3b1e1a',
      branch: '#d9a1a1',
      leaf: '#e8b4c8',
      fence: '#d9a1a1',
    },
    minecraftPalette: {
      log: 'cherry_log',
      branch: 'stripped_cherry_log',
      fence: 'cherry_fence',
      leaf: 'cherry_leaves',
    },
    params: {
      randomSeed: 417,
      colorRandomness: 0.14,
      height: 15, crownWidth: 18, crownDepth: 0.58, trunkBaseRadius: 1.8,
      trunkTaper: 0.48, trunkLean: 1, trunkLeanDirection: 150, clearTrunkHeight: 0.28, trunkCurvature: 0.11, trunkNoise: 0.12,
      primaryBranchCount: 8, branchAngle: 44, branchAngleVariance: 10,
      branchLengthRatio: 0.88, branchOrderDepth: 3, branchDensity: 0.75,
      branchDroop: 0.18, apicalDominance: 0.16,
      crownShape: 'vase', crownFullness: 0.88, leafClusterRadius: 2.4,
      leafDensity: 0.88, interiorLeafPruning: 0.24,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.5, buildabilityBias: 0.74,
    },
  },
  {
    id: 'mangrove',
    name: 'Mangrove',
    description: 'Mangrove-inspired tree with a lifted crown, crooked trunk line, and spreading irregular canopy that suggests tidal growth without needing exposed root mechanics.',
    growthForm: 'coastal irregular broadleaf',
    blockColors: {
      log: '#6b4535',
      branch: '#7b3a36',
      leaf: '#4d8b28',
      fence: '#7b3a36',
    },
    minecraftPalette: {
      log: 'mangrove_log',
      branch: 'stripped_mangrove_log',
      fence: 'mangrove_fence',
      leaf: 'mangrove_leaves',
    },
    params: {
      randomSeed: 522,
      colorRandomness: 0.18,
      height: 16, crownWidth: 16, crownDepth: 0.64, trunkBaseRadius: 2,
      trunkTaper: 0.46, trunkLean: 4, trunkLeanDirection: 220, clearTrunkHeight: 0.24, trunkCurvature: 0.22, trunkNoise: 0.26,
      primaryBranchCount: 8, branchAngle: 40, branchAngleVariance: 16,
      branchLengthRatio: 0.9, branchOrderDepth: 3, branchDensity: 0.75,
      branchDroop: 0.3, apicalDominance: 0.14,
      crownShape: 'irregular', crownFullness: 0.82, leafClusterRadius: 2.3,
      leafDensity: 0.82, interiorLeafPruning: 0.18,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.35, buildabilityBias: 0.68,
    },
  },
  {
    id: 'baobab',
    name: 'Baobab',
    description: 'Massive-trunk baobab interpretation scaled down for survival builds, with a bottle-like stem and a sparse crown perched high on stout arms.',
    growthForm: 'bottle-trunk broadleaf',
    blockColors: {
      log: '#8a6a42',
      branch: '#b9814d',
      leaf: '#6f8a3a',
      fence: '#b9814d',
    },
    minecraftPalette: {
      log: 'acacia_log',
      branch: 'stripped_acacia_log',
      fence: 'acacia_fence',
      leaf: 'acacia_leaves',
    },
    params: {
      randomSeed: 611,
      colorRandomness: 0.14,
      height: 17, crownWidth: 18, crownDepth: 0.34, trunkBaseRadius: 3,
      trunkTaper: 0.28, trunkLean: 0, trunkLeanDirection: 0, clearTrunkHeight: 0.5, trunkCurvature: 0.06, trunkNoise: 0.08,
      primaryBranchCount: 7, branchAngle: 58, branchAngleVariance: 9,
      branchLengthRatio: 0.75, branchOrderDepth: 2, branchDensity: 0.6,
      branchDroop: 0.02, apicalDominance: 0.1,
      crownShape: 'vase', crownFullness: 0.65, leafClusterRadius: 2,
      leafDensity: 0.65, interiorLeafPruning: 0.48,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.5, buildabilityBias: 0.86,
    },
  },
  {
    id: 'crazy',
    name: 'Crazy',
    description: 'Intentional wild-card preset with exaggerated lean, asymmetry, and branching energy, but still trimmed back enough that the result can be copied block-by-block.',
    growthForm: 'stylized irregular fantasy broadleaf',
    blockColors: {
      log: '#5f3d23',
      branch: '#915f2f',
      leaf: '#7aac4f',
      fence: '#915f2f',
    },
    minecraftPalette: {
      log: 'oak_log',
      branch: 'stripped_acacia_log',
      fence: 'acacia_fence',
      leaf: 'oak_leaves',
    },
    params: {
      randomSeed: 777,
      colorRandomness: 0.22,
      height: 18, crownWidth: 17, crownDepth: 0.66, trunkBaseRadius: 1.75,
      trunkTaper: 0.52, trunkLean: 10, trunkLeanDirection: 305, clearTrunkHeight: 0.2, trunkCurvature: 0.3, trunkNoise: 0.34,
      primaryBranchCount: 7, branchAngle: 54, branchAngleVariance: 18,
      branchLengthRatio: 1, branchOrderDepth: 3, branchDensity: 0.78,
      branchDroop: 0.24, apicalDominance: 0.08,
      crownShape: 'irregular', crownFullness: 0.82, leafClusterRadius: 2.4,
      leafDensity: 0.82, interiorLeafPruning: 0.22,
      minBranchThickness: 1, leafCleanup: 1, symmetryAssist: 0.02, buildabilityBias: 0.66,
    },
  },
];

/** Merge a preset's params over a base parameter set. Returns a new object. */
export function applyPreset(base: TreeParams, preset: Preset): TreeParams {
  return { ...base, ...preset.params };
}

/** Merge a preset's block colors over a base palette. Returns a new object. */
export function applyPresetBlockColors(base: BlockColors, preset: Preset): BlockColors {
  return { ...base, ...DEFAULT_PRESET_COLORS, ...preset.blockColors };
}

/** Merge a preset's Minecraft palette over a base palette. Returns a new object. */
export function applyPresetMinecraftPalette(base: MinecraftPalette, preset: Preset): MinecraftPalette {
  return { ...base, ...DEFAULT_MINECRAFT_PALETTE, ...(preset.minecraftPalette ?? {}) };
}
